//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentWebsite.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string StudentName { get; set; }
        public string Address { get; set; }
        public int Class { get; set; }
        public int Age { get; set; }
        public string Hobbies { get; set; }
        public string Gender { get; set; }
        public int CityId { get; set; }
        public string Pincode { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string Photo { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual City City { get; set; }
    }
}
